default_platform(:ios)

platform :ios do
  desc "Runs all the tests for the iOS application"
  lane :test do
    run_tests(
      project: "DevOpsPipelineApp.xcodeproj",
      scheme: "DevOpsPipelineApp",
      skip_testing: ["DevOpsPipelineAppUITests"],
      # Tell Fastlane to just find any available iPhone simulator
      device: "iPhone 15" 
    )
  end
end
