default_platform(:ios)

platform :ios do
  desc "Runs all the tests for the iOS application"
  lane :test do
    run_tests(
      project: "DevOpsPipelineApp.xcodeproj",
      scheme: "DevOpsPipelineApp",
      skip_testing: ["DevOpsPipelineAppUITests"] # This tells Fastlane to skip the flaky UI tests
    )
  end
end