default_platform(:ios)

platform :ios do
  desc "Runs all the tests for the iOS application"
  lane :test do
    run_tests(
      project: "DevOpsPipelineApp.xcodeproj",
      scheme: "DevOpsPipelineApp",
      skip_testing: ["DevOpsPipelineAppUITests"],
      device: "iPhone 17 Pro" # Updated to match your local Xcode environment
    )
  end
end
