name: Apple CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-application:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Explicitly set the Xcode version to the newest available on the runner
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3' # Updated from 15.2

      - name: Run Fastlane Test Lane
        run: fastlane test
